language: java
jdk:
  - openjdk7
before_install:
  - sudo apt-get install junit
  - curl -L https://github.com/licel/jcardsim/raw/jc2.2.2/jcardsim-2.2.2-all.jar -o test/lib/jcardsim-2.2.2-all.jar
script:
  - ant -Dtest.build.mock=1 test
